run:
  label: control
  duration_yr: 1.0e3        # 1,000 years
  dt_yr: 0.01369863         # 5 days (~73k steps total)
  output_every_steps: 200
  integrator: ias15

physics:
  gr: true                 # turn REBOUNDx off for now
  solar_j2: true           # your build lacks 'oblateness'; keep off

bodies:
  use_default_list: true
  elements_csv: solar_flyby_sim/data/j2000_elements.csv

flybys:
  enabled: false

io:
  outdir: outputs/control

logging:
  level: INFO
