run:
  label: control
  duration_yr: 2.0e7   # 20 Myr
  dt_yr: 0.004109589    # 1.5 days
  output_every_steps: 100
  densify_near_flyby: true
  seed_master: 20250808

physics:
  gr: true
  solar_j2: true
  j2_value: 2.2e-7
  solar_mass_loss: false

bodies:
  use_default_list: true
  # If false, provide your own list below

flybys:
  enabled: false  # control: off or masses /1000 handled in driver
  density_scale: 1.0
  impact_b_pc_max: 0.1
  injection_radius_pc: 1.0

io:
  outdir: outputs/control

logging:
  level: INFO